In [1]:
!pip install yfinance pandas

Requirement already satisfied: yfinance in c:\users\hp\anaconda3\lib\site-packages (0.2.65)
Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in c:\users\hp\anaconda3\lib\site-packages (from yfinance) (1.26.4)
Requirement already satisfied: requests>=2.31 in c:\users\hp\anaconda3\lib\site-packages (from yfinance) (2.32.2)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\hp\anaconda3\lib\site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\hp\anaconda3\lib\site-packages (from yfinance) (3.10.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\hp\anaconda3\lib\site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\hp\anaconda3\lib\site-packages (from yfinance) (2.4.2)
Requirement already satisfied: peewee>=3.16.2 in c:\users\hp\anaconda3\lib\site-packages (from yfinance) (3.18.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\hp\anaconda3\lib\site-packages (from yfinance) (4.12.3)
Requirement already satisfied: curl_cffi>=0.7 in c:\users\hp\anaconda3\lib\site-packages (from yfinance) (0.12.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\hp\anaconda3\lib\site-packages (from yfinance) (3.20.3)
Requirement already satisfied: websockets>=13.0 in c:\users\hp\anaconda3\lib\site-packages (from yfinance) (15.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\hp\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: cffi>=1.12.0 in c:\users\hp\anaconda3\lib\site-packages (from curl_cffi>=0.7->yfinance) (1.16.0)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\hp\anaconda3\lib\site-packages (from curl_cffi>=0.7->yfinance) (2025.7.14)
Requirement already satisfied: pycparser in c:\users\hp\anaconda3\lib\site-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.21)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hp\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.5.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

### Data Collection

In [5]:
import yfinance as yf
import pandas as pd

df = yf.download("TCS.NS", period="2y", interval="1d", auto_adjust=False, timeout=30)

# Check if data exists
if df.empty:
    print("Download failed (network issue)")
else:
    df.reset_index(inplace=True)
    df = df[df["Date"].notna()]
    
    df.to_csv("TCS_2Years.csv", index=False)
    print("TCS downloaded successfully")

[*********************100%***********************]  1 of 1 completed

TCS downloaded successfully

In [25]:
import yfinance as yf
import pandas as pd

df = yf.download("HCLTECH.NS", period="2y", interval="1d", auto_adjust=False)

df.reset_index(inplace=True)
df = df[df["Date"].notna()]

df.to_csv("HCL_2Years.csv", index=False)

print(" HCL downloaded")

[*********************100%***********************]  1 of 1 completed

 HCL downloaded

In [27]:
import yfinance as yf
import pandas as pd

df = yf.download("INFY.NS", period="2y", interval="1d", auto_adjust=False)

df.reset_index(inplace=True)
df = df[df["Date"].notna()]

df.to_csv("INFY_2Years.csv", index=False)

print("INFY downloaded")

[*********************100%***********************]  1 of 1 completed

INFY downloaded

In [1]:
import pandas as pd 
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
tcs = pd.read_csv("TCS_2years.csv")

In [3]:
tcs = tcs[tcs["Date"].notna()]
tcs.reset_index(drop=True, inplace=True)
tcs.head()

,Date,Adj Close,Close,High,Low,Open,Volume
0,2024-04-02,3642.269287109375,3883.800048828125,3909.85009765625,3873.0,3890.0,2142666
1,2024-04-03,3701.820068359375,3947.300048828125,3981.0,3851.0,3851.0,3973090
2,2024-04-04,3754.33740234375,4003.300048828125,4028.64990234375,3935.25,3975.89990234375,3394637
3,2024-04-05,3731.783203125,3979.25,4002.0,3960.5,3978.0,1636819
4,2024-04-08,3725.499755859375,3972.550048828125,4032.64990234375,3960.0,3983.0,2302538

In [4]:
hcl = pd.read_csv("HCL_2years.csv")

In [5]:
hcl = hcl[hcl["Date"].notna()]
hcl.reset_index(drop=True, inplace=True)
hcl.head()

,Date,Adj Close,Close,High,Low,Open,Volume
0,2024-04-02,1422.0706787109375,1528.300048828125,1565.0,1525.0999755859375,1559.0,2031775
1,2024-04-03,1429.095947265625,1535.8499755859375,1558.449951171875,1518.0,1525.3499755859375,3343884
2,2024-04-04,1432.6318359375,1539.6500244140625,1552.5,1518.699951171875,1540.800048828125,3388449
3,2024-04-05,1437.8424072265625,1545.25,1547.699951171875,1523.800048828125,1542.449951171875,2773570
4,2024-04-08,1433.0037841796875,1540.050048828125,1554.0,1537.6500244140625,1554.0,1820136

In [6]:
infy = pd.read_csv("INFY_2years.csv")

In [7]:
infy = infy[infy["Date"].notna()]
infy.reset_index(drop=True, inplace=True)
infy.head()

,Date,Adj Close,Close,High,Low,Open,Volume
0,2024-04-02,1396.080810546875,1482.8499755859375,1493.1500244140625,1480.8499755859375,1484.8499755859375,7279400
1,2024-04-03,1394.0096435546875,1480.6500244140625,1495.0999755859375,1475.0,1479.0,8736248
2,2024-04-04,1399.7054443359375,1486.699951171875,1495.6500244140625,1468.0,1490.550048828125,11186915
3,2024-04-05,1392.55029296875,1479.0999755859375,1486.699951171875,1476.050048828125,1480.050048828125,5072482
4,2024-04-08,1390.2906494140625,1476.699951171875,1490.949951171875,1474.0999755859375,1483.0,6610887

In [8]:
tcs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 496 entries, 0 to 495
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       496 non-null    object
 1   Adj Close  496 non-null    object
 2   Close      496 non-null    object
 3   High       496 non-null    object
 4   Low        496 non-null    object
 5   Open       496 non-null    object
 6   Volume     496 non-null    object
dtypes: object(7)
memory usage: 27.3+ KB

In [16]:
hcl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 496 entries, 0 to 495
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       496 non-null    object
 1   Adj Close  496 non-null    object
 2   Close      496 non-null    object
 3   High       496 non-null    object
 4   Low        496 non-null    object
 5   Open       496 non-null    object
 6   Volume     496 non-null    object
dtypes: object(7)
memory usage: 27.3+ KB

In [19]:
infy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 496 entries, 0 to 495
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       496 non-null    object
 1   Adj Close  496 non-null    object
 2   Close      496 non-null    object
 3   High       496 non-null    object
 4   Low        496 non-null    object
 5   Open       496 non-null    object
 6   Volume     496 non-null    object
dtypes: object(7)
memory usage: 27.3+ KB

### Data Cleaning

In [22]:
tcs["Date"] = pd.to_datetime(tcs["Date"])
hcl["Date"] = pd.to_datetime(hcl["Date"])
infy["Date"] = pd.to_datetime(infy["Date"])

In [24]:
cols = ["Adj Close", "Close", "High", "Low", "Open", "Volume"]

tcs[cols] = tcs[cols].apply(pd.to_numeric)
hcl[cols] = hcl[cols].apply(pd.to_numeric)
infy[cols] = infy[cols].apply(pd.to_numeric)

### Data Merging

In [27]:
tcs["Company"] = "TCS"
hcl["Company"] = "HCL"
infy["Company"] = "INFY"

In [29]:
final_df = pd.concat([tcs, hcl, infy])
final_df.reset_index(drop=True, inplace=True)

In [31]:
final_df.head(10)

,Date,Adj Close,Close,High,Low,Open,Volume,Company
0,2024-04-02,3642.269287,3883.800049,3909.850098,3873.000000,3890.000000,2142666,TCS
1,2024-04-03,3701.820068,3947.300049,3981.000000,3851.000000,3851.000000,3973090,TCS
2,2024-04-04,3754.337402,4003.300049,4028.649902,3935.250000,3975.899902,3394637,TCS
3,2024-04-05,3731.783203,3979.250000,4002.000000,3960.500000,3978.000000,1636819,TCS
4,2024-04-08,3725.499756,3972.550049,4032.649902,3960.000000,3983.000000,2302538,TCS
5,2024-04-09,3701.116699,3946.550049,4015.850098,3925.050049,3984.000000,1876992,TCS
6,2024-04-10,3736.847412,3984.649902,3990.199951,3918.000000,3956.399902,2101965,TCS
7,2024-04-12,3752.555664,4001.399902,4013.350098,3945.500000,3971.000000,4354821,TCS
8,2024-04-15,3696.099854,3941.199951,4064.199951,3919.050049,4001.399902,4200329,TCS
9,2024-04-16,3631.953369,3872.800049,3928.699951,3862.850098,3902.000000,3051420,TCS

### Feature engineering

###### Measures profit/loss over time

In [35]:
final_df["Daily Return"] = final_df.groupby("Company")["Close"].pct_change() * 100

###### MA_7(7 day Moving Average) needs 7 values and MA_30(30 days Moving Averages) needs 30 values

In [38]:
final_df["MA_7"] = final_df.groupby("Company")["Close"] \
    .rolling(7).mean().reset_index(level=0, drop=True)

final_df["MA_30"] = final_df.groupby("Company")["Close"] \
    .rolling(30).mean().reset_index(level=0, drop=True)

###### Measures how much price fluctuates

In [41]:
final_df["Volatility"] = final_df["High"] - final_df["Low"]

In [43]:
final_df["Month"] = final_df["Date"].dt.month
final_df["Year"] = final_df["Date"].dt.year

###### Shows total growth over time

In [46]:
final_df["Cumulative Return"] = final_df.groupby("Company")["Daily Return"] \
    .transform(lambda x: (1 + x/100).cumprod())

###### Shows actual gain/loss in Rs.

In [49]:
final_df["Price Change"] = final_df.groupby("Company")["Close"].diff()

###### High-Low Percentage (Volatility %)

In [52]:
final_df["HL_Pct"] = ((final_df["High"] - final_df["Low"]) / final_df["Close"]) * 100

###### Based on MA crossover

In [55]:
final_df["Trend"] = final_df["MA_7"] > final_df["MA_30"]

###### Exponential Moving Average (EMA)

In [58]:
final_df["EMA_7"] = final_df.groupby("Company")["Close"].transform(lambda x: x.ewm(span=7, adjust=False).mean())

### Comparison

##### Average Return per company

In [62]:
final_df.groupby("Company")["Daily Return"].mean()

Company
HCL    -0.005585
INFY   -0.014326
TCS    -0.084023
Name: Daily Return, dtype: float64

###### HCL has the best average return (least negative)
###### Infosys performs moderately
###### TCS shows the lowest returns

##### Risk (Volatility)

In [66]:
final_df.groupby("Company")["HL_Pct"].mean()

Company
HCL     2.117437
INFY    1.961274
TCS     1.801914
Name: HL_Pct, dtype: float64

###### HCL is the most volatile (risky) 
###### TCS is the most stable

##### Total Growth (Cumulative Return)

In [70]:
final_df.groupby("Company")["Cumulative Return"].last()

Company
HCL     0.917490
INFY    0.877230
TCS     0.631006
Name: Cumulative Return, dtype: float64

###### HCL shows the highest overall growth
###### TCS shows the lowest growth

##### Trading Activity

In [74]:
final_df.groupby("Company")["Volume"].mean()

Company
HCL     3.038039e+06
INFY    7.993220e+06
TCS     2.717831e+06
Name: Volume, dtype: float64

###### Infosys is the most actively traded stock

##### Trend Strength

In [78]:
final_df.groupby("Company")["Trend"].mean()

Company
HCL     0.544355
INFY    0.524194
TCS     0.375000
Name: Trend, dtype: float64

###### HCL stays in uptrend more frequently
###### TCS shows weaker trend behavior

### INSIGHT:
##### Among the three companies, HCL demonstrates better overall performance with higher returns and growth, but at the cost of higher volatility. Infosys shows moderate performance with high trading activity, while TCS appears more stable but delivers lower returns and weaker trend strength.

In [82]:
final_df

,Date,Adj Close,Close,High,Low,Open,Volume,Company,Daily Return,MA_7,MA_30,Volatility,Month,Year,Cumulative Return,Price Change,HL_Pct,Trend,EMA_7
0,2024-04-02,3642.269287,3883.800049,3909.850098,3873.000000,3890.000000,2142666,TCS,NaN,NaN,NaN,36.850098,4,2024,NaN,NaN,0.948816,False,3883.800049
1,2024-04-03,3701.820068,3947.300049,3981.000000,3851.000000,3851.000000,3973090,TCS,1.634997,NaN,NaN,130.000000,4,2024,1.016350,63.500000,3.293390,False,3899.675049
2,2024-04-04,3754.337402,4003.300049,4028.649902,3935.250000,3975.899902,3394637,TCS,1.418691,NaN,NaN,93.399902,4,2024,1.030769,56.000000,2.333073,False,3925.581299
3,2024-04-05,3731.783203,3979.250000,4002.000000,3960.500000,3978.000000,1636819,TCS,-0.600756,NaN,NaN,41.500000,4,2024,1.024576,-24.050049,1.042910,False,3938.998474
4,2024-04-08,3725.499756,3972.550049,4032.649902,3960.000000,3983.000000,2302538,TCS,-0.168372,NaN,NaN,72.649902,4,2024,1.022851,-6.699951,1.828798,False,3947.386368
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1483,2026-03-25,1279.099976,1279.099976,1290.599976,1257.099976,1270.000000,10824030,INFY,0.062577,1255.842878,1307.190007,33.500000,3,2026,0.862596,0.799927,2.619029,False,1265.108869
1484,2026-03-27,1269.699951,1269.699951,1294.800049,1263.199951,1285.199951,13092541,INFY,-0.734894,1261.100010,1300.450004,31.600098,3,2026,0.856257,-9.400024,2.488785,False,1266.256640
1485,2026-03-30,1250.599976,1250.599976,1265.500000,1243.000000,1250.000000,14108486,INFY,-1.504290,1258.742868,1295.936670,22.500000,3,2026,0.843376,-19.099976,1.799136,False,1262.342474
1486,2026-04-01,1275.699951,1275.699951,1303.000000,1269.500000,1290.000000,8137156,INFY,2.007035,1266.585711,1292.823336,33.500000,4,2026,0.860303,25.099976,2.626009,False,1265.681843
1487,2026-04-02,1300.800049,1300.800049,1305.400024,1259.800049,1260.000000,12869828,INFY,1.967555,1273.000000,1290.663338,45.599976,4,2026,0.877230,25.100098,3.505533,False,1274.461394

In [84]:
final_df.to_csv("final_stock_data.csv", index=False)

In [1]:
#### !pip install pandoc

Collecting pandoc
  Downloading pandoc-2.4.tar.gz (34 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting plumbum (from pandoc)
  Downloading plumbum-1.10.0-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: ply in c:\users\hp\anaconda3\lib\site-packages (from pandoc) (3.11)
Requirement already satisfied: pywin32 in c:\users\hp\anaconda3\lib\site-packages (from plumbum->pandoc) (305.1)
Downloading plumbum-1.10.0-py3-none-any.whl (127 kB)
Building wheels for collected packages: pandoc
  Building wheel for pandoc (setup.py): started
  Building wheel for pandoc (setup.py): finished with status 'done'
  Created wheel for pandoc: filename=pandoc-2.4-py3-none-any.whl size=34823 sha256=12404b5685f32758edcb5a88da0c29f33366229e56dcce767281ecee76936cf8
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\9c\2f\9f\b1aac8c3e74b4ee327dc8c6eac5128996f9eadf586e2c0ba67
Successfully built pandoc
Installing collected packages: plumbum, pandoc

   ---------------------------------------- 0/2 [plumbum]
   ---------------------------------------- 0/2 [plumbum]
   ---------------------------------------- 0/2 [plumbum]
   -------------------- ------------------- 1/2 [pandoc]
   -------------------- ------------------- 1/2 [pandoc]
   ---------------------------------------- 2/2 [pandoc]

Successfully installed pandoc-2.4 plumbum-1.10.0

  DEPRECATION: Building 'pandoc' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'pandoc'. Discussion can be found at https://github.com/pypa/pip/issues/6334

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip